
version=1.3.1
group=io.github.alexzhirkevich

#Gradle
org.gradle.jvmargs=-Xmx8128M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx8128M"

#Kotlin
kotlin.code.style=official
jvmTarget=11

#Android
android.useAndroidX=true
android.compileSdk=37
android.targetSdk=37
android.minSdk=24
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.newDsl=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL


org.jetbrains.compose.experimental.macos.enabled=true

